### ISSUE TITLE
Alternative of Timer0 Example

### ISSUE THREAD

**Issue by iledesma08** [GabrielEValenzuela/MicrocontrollerExamples#24]
> @GabrielEValenzuela considering the configuration``match_cfg_struct.ExtMatchOutputType = TIM_EXTMATCH_TOGGLE;``, wouldnt it be better to connect the LEDs to the Match pins instead of doing the toggle through the Interruption Handler? I mean, for Match0 of Timer0, we connect LED0 to P1.28, then LED1 to P1.29, and so on. 

 _Originally posted by @iledesma08 in [8bf64a0](https://github.com/GabrielEValenzuela/MicrocontrollerExamples/commit/8bf64a049e1a71e055002c255ae19b0f2fa219d8#r148056246)_

**Comment by GabrielEValenzuela** [comment]
I like the approach, could you implement it?
